name: 'dq_tools'
config-version: 2
version: '1.2.0'
require-dbt-version: ">=1.6.0"

test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"
model-paths: ["models"]

vars:
  # dq_tools_enable_store_test_results: true
  # dbt_dq_tool_schema: dq_raw
  # dbt_dq_tool_database: dq_tools
  # dbt_dq_tool_full_refresh: false
  # >> for test coverage
  # dbt_dq_tool_test_coverage_exclusion:
  #   by_database_fqn: []
  #   by_schema_fqn: []
  #   by_table_fqn: []
  # >> for metricflow
  # dbt_dq_tool_start_date
  # dbt_dq_tool_end_date
  # dq_tools__auto_generate_test_description: 1 # Set 1 to automatically generate test description if not specified

models:
  dq_tools:
    +database: "{{ var('dbt_dq_tool_database', target.database) }}"
    +schema: "{{ var('dbt_dq_tool_schema', target.schema) }}"
