name: dbt action
description: Run and schedule dbt commands directly in your Github repo
author: Dat Nguyen

inputs:
  dbt_command:
    description: dbt command
    default: dbt run --profiles-dir .
    required: true
  dbt_project_folder:
    description: dbt project folder. Defaults to .
    default: .
    required: false
  dbt_profile_dir:
    description: dbt profile folder. Defaults to .
    default: .
    required: false
  version:
    description: dbt version
    default: 1.3
    required: true
  adapter:
    description: dbt adapter name
    default: snowflake
    required: true

outputs:
  result:
    description: Success or failure of the dbt command

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.dbt_command }}
    - ${{ inputs.dbt_project_folder }}
    - ${{ inputs.dbt_profile_dir }}

branding:
  icon: database
  color: purple