name: "dbt action"
description: "Run and schedule dbt commands directly in your Github repo"
author: "Dat Nguyen"

inputs:
  dbt_command:
    description: "dbt command"
    default: "dbt run --profiles-dir ."
    required: true
  dbt_project_folder:
    description: "dbt project folder. Defaults to ."
    default: "."
    required: false
  dbt_profile_dir:
    description: "dbt profile folder. Defaults to ."
    default: "."
    required: false
  dbt_adapter:
    description: "Specify dbt docker image name"
    default: "dbt-snowflake:1.2.latest"
    required: true
outputs:
  result:
    description: "Success or failure of the dbt command"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dbt_command }}
    - ${{ inputs.dbt_project_folder }}
    - ${{ inputs.dbt_profile_dir }}
  env:
    DBT_ADAPTER: ${{ inputs.dbt_adapter }}
branding:
  icon: 'database'  
  color: 'purple'