name: testing on pull request (new)

on:
  pull_request:
    branches: [ "main" ]

jobs:
  snowflake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}-snowflake
          path: .cache
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.7.1

      - name: Install dependencies
        run: |
          poetry config installer.max-workers 1
          poetry config virtualenvs.in-project true
          poetry install

      - name: Test dq-tools
        run: poetry run poe dq-tools-test-snowflake
        env:
          DBT_SNOWFLAKE_TEST_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_TEST_ACCOUNT }}
          DBT_SNOWFLAKE_TEST_USER: ${{ secrets.DBT_SNOWFLAKE_TEST_USER }}
          DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD: ${{ secrets.DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD }}
          DBT_SNOWFLAKE_TEST_ROLE: ${{ secrets.DBT_SNOWFLAKE_TEST_ROLE }}
          DBT_SNOWFLAKE_TEST_DATABASE: ${{ secrets.DBT_SNOWFLAKE_TEST_DATABASE }}
          DBT_SNOWFLAKE_TEST_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_TEST_WAREHOUSE }}
          DBT_SCHEMA: PRCI_${{ github.sha }}

  bigquery:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}-bigquery
          path: .cache
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.7.1

      - name: Install dependencies
        run: |
          poetry config installer.max-workers 1
          poetry config virtualenvs.in-project true
          poetry install

      - name: Test dq-tools
        run: poetry run poe dq-tools-test-bigquery
        env:
          DBT_SNOWFLAKE_TEST_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_TEST_ACCOUNT }}
          DBT_SNOWFLAKE_TEST_USER: ${{ secrets.DBT_SNOWFLAKE_TEST_USER }}
          DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD: ${{ secrets.DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD }}
          DBT_SNOWFLAKE_TEST_ROLE: ${{ secrets.DBT_SNOWFLAKE_TEST_ROLE }}
          DBT_SNOWFLAKE_TEST_DATABASE: ${{ secrets.DBT_SNOWFLAKE_TEST_DATABASE }}
          DBT_SNOWFLAKE_TEST_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_TEST_WAREHOUSE }}
          DBT_SCHEMA: PRCI_${{ github.sha }}
