name: ci_integration_tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry:
          - ghcr.io/dbt-labs/
        dbt_adapter:
          - dbt-snowflake:1.2.latest
          # - dbt-snowflake:1.3.latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare environment
        run: chmod +x run_test.sh

      - name: Run integration test
        uses: ${{ matrix.registry }}${{ matrix.dbt_adapter }}
        run: ./run_test.sh snowflake
        env:
          DBT_SNOWFLAKE_TEST_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_TEST_ACCOUNT }}
          DBT_SNOWFLAKE_TEST_USER: ${{ secrets.DBT_SNOWFLAKE_TEST_USER }}
          DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD: ${{ secrets.DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD }}
          DBT_SNOWFLAKE_TEST_ROLE: ${{ secrets.DBT_SNOWFLAKE_TEST_ROLE }}
          DBT_SNOWFLAKE_TEST_DATABASE: ${{ secrets.DBT_SNOWFLAKE_TEST_DATABASE }}
          DBT_SNOWFLAKE_TEST_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_TEST_WAREHOUSE }}
