name: ci_integration_tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  prometheus:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        adapter: ["snowflake"]
        version: ["1.3"] #"1.4" doesn't have latest tag yet
    container:
      image: "ghcr.io/dbt-labs/dbt-${{ matrix.adapter }}:${{ matrix.version }}.latest"
    steps:
      - uses: actions/checkout@v3

      - name: Run integration test
        run: |
          chmod +x run_test.sh
          cp -fr ./integration_tests/packages_${{ matrix.version }}.yml ./integration_tests/packages.yml
          ./run_test.sh ${{ matrix.adapter }}
        env:
          DBT_SNOWFLAKE_TEST_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_TEST_ACCOUNT }}
          DBT_SNOWFLAKE_TEST_USER: ${{ secrets.DBT_SNOWFLAKE_TEST_USER }}
          DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD: ${{ secrets.DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD }}
          DBT_SNOWFLAKE_TEST_ROLE: ${{ secrets.DBT_SNOWFLAKE_TEST_ROLE }}
          DBT_SNOWFLAKE_TEST_DATABASE: ${{ secrets.DBT_SNOWFLAKE_TEST_DATABASE }}
          DBT_SNOWFLAKE_TEST_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_TEST_WAREHOUSE }}
          DBT_SCHEMA: PRCI_${{ github.sha }}
          
  poseidon:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        adapter: ["bigquery"]
        version: ["1.3"] #"1.4" doesn't have latest tag yet
    container:
      image: "ghcr.io/dbt-labs/dbt-${{ matrix.adapter }}:${{ matrix.version }}.latest"
    steps:
      - uses: actions/checkout@v3

      - name: Set up credentials
        run: |
          echo $DBT_ENV_SECRET_BIGQUERY_SERVICE_KEY_JSON | base64 -d > /opt/bigquery_service_key.json
        env:
          DBT_ENV_SECRET_BIGQUERY_SERVICE_KEY_JSON: ${{ secrets.DBT_ENV_SECRET_BIGQUERY_SERVICE_KEY_JSON }}

      - name: Run integration test
        run: |
          chmod +x run_test.sh
          cp -fr ./integration_tests/packages_${{ matrix.version }}.yml ./integration_tests/packages.yml
          ./run_test.sh ${{ matrix.adapter }}
        env:
          DBT_ENV_SECRET_BIGQUERY_SERVICE_KEY_PATH: /opt/bigquery_service_key.json
          DBT_BIGQUERY_TEST_DATABASE: ${{ secrets.DBT_BIGQUERY_TEST_DATABASE }}
          DBT_SCHEMA: PRCI_${{ github.sha }}